sudo: required
dist: trusty
services:
  - docker

language: go
go:
  - "1.14"

before_install:
  - curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v${KUBERNETES_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/

script:
  - make ci

env:
  global:
    - KIND_VERSION=v0.7.0

matrix:
  include:
    - env: KUBERNETES_VERSION=1.15.7
    - env: KUBERNETES_VERSION=1.16.4
    - env: KUBERNETES_VERSION=1.17.0
    - env: KUBERNETES_VERSION=1.18.0