sudo: required
dist: trusty
services:
  - docker

language: go
go:
  - "1.12.1"

before_install:
  - curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/0.2.0/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBERNETES_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/

script:
  - make ci

env:
  global:
    - GO111MODULE=on
    - MINIKUBE_VERSION=v0.35.0
    - KUBERNETES_VERSION=1.12.5
